### ISSUE TITLE
Unable to Login or Register User

### ISSUE THREAD

**Issue by sunilysk** [Kbwebs/MultiAuth#12]
I am getting a error while trying to register a new User

Argument 1 passed to Illuminate\Auth\Guard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, none given

When i try to login, it always give me message which reads "These credentials do not match our records." although i created user via tinker

Please refer my repository if you need more details 
https://github.com/sunilysk/auth

**Comment by kasperbasse** [comment]
Hi @sunilysk 
I found the problem with your code, and the problem is in your AuthController:
Http/Controllers/Auth/AuthController.php

**Registration:**
Try to copy this method from, into your AuthController:
vendor/laravel/framework/src/Illuminate/Foundation/Auth/RegistersUsers.php
Method: postRegister
After you have copied this method into your AuthController, then you must change:
``Auth::login($this->create($request->all()));``
To, and this is an example, user() or admin():
``Auth::user()->login($this->create($request->all()));``
And the registration will work just fine. :)

**Login:**
Try to copy this method from, into your AuthController:
vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php
Method: postLogin
After you have copied this method into your AuthController, then you must change:
``Auth::attempt($credentials, $request->has('remember'))``
To, and this is an example, user() or admin():
``Auth::user()->attempt($credentials, $request->has('remember'))``
And the login will work just fine. :)

Hope this helps on your problem :)

**Comment by sunilysk** [comment]
Hi @kasperbasse,

Honestly, i did not expected the response will be that quick!!!. Thank You very much..

I was able to to figure out the real problem with my code, looking at your explanation.

I am working on the repository, to make it easier for someone new to Laravel ( like me) easier to implement your code.
