### ISSUE TITLE
Reset Password Issue

### ISSUE THREAD

**Issue by sunilysk** [Kbwebs/MultiAuth#15]
Hi @kasperbasse,

I was able to separate different types of users with your help, but now i am facing problem while implementing reset password. The hidden token field of the ``` auth.reset ``` view is putting ``` user ``` as token value instead of the ``` token ```. I am not sure where am i incorrect. Please find the attached screenshot.
![issue](https://cloud.githubusercontent.com/assets/11918693/10399018/ddd032a6-6ecd-11e5-888b-e43c3135435e.JPG)

My second question is about adding different view types for different types of users. Do i need to add it as an array to ``` password ``` value in ``` auth.php ``` file
``` 'password' => [
        'email' =>[ 'emails.users.password',  'emails.admins.password', 'emails.users.password']
        'table' => 'password_resets',
        'expire' => 60,] ```
 
Please help me with this. For my code, refer https://github.com/sunilysk/auth

**Comment by kasperbasse** [comment]
Hello @sunilysk 
Your problem is that your code needs to support that route: 
Route::get('password/reset/{type}/{token}', 'Auth\PasswordController@getReset');
The solution for your problem is in the getReset method, you will have to modify your code like this:
```
public function getReset($userType, $token = null)
{
    if (is_null($token)) {
        throw new NotFoundHttpException;
    }
    return view('auth.reset')->with(['token' => $token, 'type' => $userType]);
}
```
For your second problem, with password you will have to add: 
'emails.users.password' in the multi auth array like this:
```
'multi-auth' => [
	'admin' => [
		'driver' => 'eloquent',
		'model'  => App\Admin::class,
		'email'  => 'emails.admins.password'
 	],
	'user' => [
		'driver' => 'eloquent',
		'model'  => App\User::class,
		'email'  => 'emails.users.password' 
	],
	'other' => [ 
		'driver' => 'eloquent',
		'model'  => App\Other::class
	]
]
```
Hope this helps with your problem.
Maybe my documentation isn't that good, i will try to update it soon :)

**Comment by sunilysk** [comment]
Hello @kasperbasse,

Thank you very much. my first question was bit silly though. :) 

I am about to complete the project https://github.com/sunilysk/auth , this project will help new users grasp your code pretty easily..

Thank You
